### ISSUE TITLE
What versions of gcc and nvcc are required?

### ISSUE THREAD

**Issue by algebravic** [FeanorTheElf/fplll-cuda-enumeration#2]
I'm trying to build.  When I used GCC version 9, the configure file didn't like it (it said that it couldn't build a test program).  When I used GCC version 11, configure seemed to like it.  However, when I tried to use make (even using the latest nvcc version 11.4) nvcc terminated saying that it can't use any version of gcc after version 7.  Can you be specific about the versions necessary?

**Comment by FeanorTheElf** [comment]
I have built the code in the following configurations

- gcc 7.5 and cuda 9.1
- gcc 9.3 and cuda 10.1

However it should work with all versions of cuda >= 9. In the end, the problem seems to be that your version of gcc 9 does not like the configure file. I am not an expert in autotools, but if you show me the detailed error message, then I can have a look tomorrow.

**Comment by algebravic** [comment]
Hi Simon, I was able to (finally) successfully build it with GCC/10.3 and
cuda/10.1.  Apparently our local setup had neglected to set LIBRARY_PATH to
point to the cuda libraries.  When I fixed that, things built ok.

Victor

PS. Is there a test program for the libraries, or should I just build fplll
with it, and run some tests there?

**Comment by FeanorTheElf** [comment]
Nice to hear that! There should be an exectuable `cudaenum_test` which runs some basic tests, however does not use GPU computations so far. To test that, you will have to build fplll.

**Comment by algebravic** [comment]
I tried running cudaenum, but it just sat there not seeming to do
anything.  Does it have an argument it takes?

Victor

**Comment by FeanorTheElf** [comment]
You mean the test executable? That should be called cudaenum_test, and should print something on the console...

**Comment by algebravic** [comment]
Right now cudaenum_test is running and using 100% of the cpu, but it isn't
printing anything.  About how long do I need to let it run before it prints
something?

**Comment by algebravic** [comment]
Ok, I was too impatient.  It just finished with "all tests successful".

**Comment by FeanorTheElf** [comment]
No problem :) Really it should not take too long on a reasonable system...

**Comment by algebravic** [comment]
It looks like the output was buffered.  Is there a setting when I'm
configuring to get the output unbuffered?

**Comment by algebravic** [comment]
I wonder if I'm running into a problem because I'm running on an AWS node.
Below is the output.  Is that what you would expect?

Enumerating 12 dimensional lattice using cuda, started 64 block with 128
threads each; Beginning with 165 start points
Got 6 new solution points and can decrease enum bound to 63554
Currently searched 7, 15, 21, 29, 57, 122, 228, 313, 426, 444, 382, 235, 0,
0, 0, 0, 0, 0, 0, 0,
Enumeration done in 5 ms
Searched 2279 tree nodes, and decreased enumeration bound down to 252.099
profiling counter 0 Gcycles, 0 Gcycles
test_small() successful!

Enumerating 33 dimensional lattice using cuda, started 64 block with 128
threads each; Beginning with 15540 start points
Got 1 new solution points and can decrease enum bound to 130305
Got 1 new solution points and can decrease enum bound to 124267
Got 1 new solution points and can decrease enum bound to 123951
Got 1 new solution points and can decrease enum bound to 115421
Got 2 new solution points and can decrease enum bound to 111726
Got 1 new solution points and can decrease enum bound to 103933
Got 1 new solution points and can decrease enum bound to 102216
Got 1 new solution points and can decrease enum bound to 101177
Got 2 new solution points and can decrease enum bound to 93250
Currently searched 12, 28, 94, 279, 772, 2021, 5097, 12692, 27598, 55457,
113935, 207371, 340416, 548010, 857157, 1288120, 1687683, 2010878, 2130904,
2398516, 2629974, 2681663, 2470829, 2098063, 1530088, 1171387, 839585,
529420, 289615, 153327, 73689, 35404, 15716, 0, 0, 0, 0, 0, 0, 0,
Enumeration done in 184 ms
Searched 26205800 tree nodes, and decreased enumeration bound down to
305.369
profiling counter 0 Gcycles, 0 Gcycles
test_knapsack() successful!

Enumerating 12 dimensional lattice using cuda, started 64 block with 128
threads each; Beginning with 17 start points
Got 5 new solution points and can decrease enum bound to 63554
Currently searched 6, 10, 10, 10, 17, 28, 42, 65, 73, 62, 51, 25, 0, 0, 0,
0, 0, 0, 0, 0,
Enumeration done in 2 ms
Searched 399 tree nodes, and decreased enumeration bound down to 252.099
profiling counter 0 Gcycles, 0 Gcycles
Enumerating 12 dimensional lattice using cuda, started 64 block with 128
threads each; Beginning with 61 start points
Got 5 new solution points and can decrease enum bound to 65215
Currently searched 6, 10, 17, 20, 36, 77, 149, 187, 230, 222, 170, 97, 0,
0, 0, 0, 0, 0, 0, 0,
Enumeration done in 2 ms
Searched 1221 tree nodes, and decreased enumeration bound down to 255.372
profiling counter 0 Gcycles, 0 Gcycles
test_small_pruning() successful!

=============
All test successfull!

**Comment by FeanorTheElf** [comment]
Yes, that is exactly what I would expect. The output is not explicitly buffered, just written to `std::cout`. Could it be the case that your AWS node or the interface buffer the output?

**Comment by algebravic** [comment]
It's very possible.  I'm not sure about all of the machinations of the AWS
node :-)
